package caseclass

/**
  * CSV文件专用模型样例类
  * @Author: Cedaris
  * @Date: 2019/8/22 10:14
  */
case class ModelFeatureCsv(
                            audience_id: Long,
                            item_id:Long,
                            click: Int,
                            city: String,
                            value_type: String,
                            frequence_type: String,
                            cate1_prefer: String,
                            cate2_prefer: String,
                            weights_cate1_prefer: String,
                            weights_cate2_prefer: String,
                            cate2Id: String,
                            ctr_1d: Double,
                            uv_ctr_1d: Double,
                            play_long_1d: Double,
                            play_times_1d: Double,
                            ctr_1w: Double,
                            uv_ctr_1w: Double,
                            play_long_1w: Double,
                            play_times_1w: Double,
                            ctr_2w: Double,
                            uv_ctr_2w: Double,
                            play_long_2w: Double,
                            play_times_2w: Double,
                            ctr_1m: Double,
                            uv_ctr_1m: Double,
                            play_long_1m: Double,
                            play_times_1m: Double,
                            matchScore: Double,
                            popScore: Double,
                            exampleAge: Double,
                            cate2Prefer: Double,
                            catePrefer: Double,
                            authorPrefer: Double,
                            position: String,
                            triggerNum: Double,
                            triggerRank: Double,
                            hour: String,
                            phoneBrand: String,
                            phoneResolution: String,
                            timeSinceLastWatchSqrt: Double,
                            timeSinceLastWatch: Double,
                            timeSinceLastWatchSquare: Double,
                            behaviorCids: String,
                            behaviorC1ids: String,
                            behaviorAids: String,
                            behaviorVids: String,
                            behaviorTokens: String,
                            videoId: Long,
                            authorId: Long,
                            cate1Id: Long,
                            cateId: Long
                          )
